export async function onRequestPost(context) {
  const API_KEY = context.env.GEMINI_API_KEY;
  
  // Updated to the most universally compatible model ID for v1beta
  const MODEL = "gemini-1.5-flash"; 
  const URL = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${API_KEY}`;

  try {
    const { message, contextData } = await context.request.json();

    const systemPrompt = `
You are the FIMA Bulking Services AI Dashboard Assistant. 

IDENTITY & TONE:
- Maintain a highly professional, executive, and helpful tone. 
- Use clear and formal language suitable for a chemical storage facility operations team.
- STRICT RULE: Do not use Markdown formatting for emphasis. Do not use double asterisks (**) or underscores (_) for bold or italic text. Use plain text only.
- Ensure all temperature units are written as °C without bolding.

CAPABILITIES & SCOPE:
- Primary Goal: Analyze and answer questions about the Current Dashboard Data provided.
- General Knowledge: You are authorized to answer random or general questions to be a helpful thought partner. 
- Professional Versatility: If the user asks a random question, answer it politely and intelligently, but always maintain your persona as an industrial assistant.
- Safety: If you notice tanks exceeding 60°C in the context data, prioritize mentioning them as critical.

CURRENT CONTEXT:
- Current Dashboard Data: ${contextData}
- User message: ${message}

Please provide your professional response below in plain text:
    `.trim();

    const response = await fetch(URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: systemPrompt
          }]
        }]
      })
    });

    const data = await response.json();

    // If the error persists, it's often because the 'models/' prefix is required or excluded in different API versions
    if (data.error) {
        // Fallback: If 1.5 fails, try the older but stable gemini-pro model naming
        return new Response(JSON.stringify({ 
          error: "AI Error: " + data.error.message + ". Check if your API Key has access to " + MODEL
        }), { status: 200 });
    }

    if (!data.candidates || data.candidates.length === 0) {
        return new Response(JSON.stringify({ error: "No response generated by AI." }), { status: 200 });
    }

    const aiText = data.candidates[0].content.parts[0].text;
    
    return new Response(JSON.stringify({ reply: aiText }), {
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error) {
    return new Response(JSON.stringify({ error: "System Error: " + error.message }), { 
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}
